### ISSUE TITLE
Can we add a software license to this repo?

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/BusRSVP#23]
Can we add a software license to this repo?

**Comment by ajwhite** [comment]
Certainly! Feel free to open a PR if you'd like to add one, otherwise we can wait for someone to pick up this issue. Looks like this project hasn't seen much activity in the recent months.

We've been using AGPL licensing, https://github.com/SandersForPresident/BernieBNB/blob/master/LICENSE.txt for reference

**Comment by jasnow** [comment]
ok

**Comment by jasnow** [comment]
Now included in PR #24 .

**Comment by jasnow** [comment]
PR #24 added a license so closing this ticket.
